export { createClient } from "lib/client";
export type { ClientOptions } from "lib/client";
export { DEFAULT_API_BASE_URL, DEFAULT_INTERNAL_API_BASE_URL } from "./lib/constants";
export type {
  Video,
  VideoAttachment,
  VideoDownloadUrls,
  VideoSubtitles,
  VideoTranscript,
  VideoMetadata,
  Playlist,
  MenuItem,
  Settings,
  Portal,
  PortalDisplay,
  PortalHero,
  CustomRedirect,
  AnalyticsProvider,
  PortalLayout,
  PortalNavigation,
  PortalTheme,
  AssistantConfig,
  ThemeConfig,
  ThemeColors,
  Account,
  AccountAI,
  Segment,
  Source,
  Citation,
  AIUsage,
  AIEvent,
  AIResponse,
  ChatOptions,
  SearchOptions,
  AIContextMessage,
  RecommendationsOptions,
  RecommendationsResponse,
  Recommendation,
  RecommendationVideo,
  // Deprecated type aliases (kept for backward compatibility)
  AskOptions,
  RecommendOptions,
  RecommendResponse,
  Conversation,
  ConversationMessage,
  ConversationMetadata,
  // Viewers API
  Viewer,
  ViewerProgress,
  ListProgressOptions,
  CreateViewerData,
  UpdateViewerData,
  SaveProgressData,
  ProgressListMeta,
  // Video list options
  ListVideosOptions,
  ListVideosLatestOptions,
  ListVideosIndexOptions,
  // Community API
  Post,
  PostAuthor,
  Comment,
  ReactionResponse,
  ListPostsOptions,
  CreatePostData,
  UpdatePostData,
  CreateCommentData,
} from "./lib/types";

export type { ViewerLookupParams } from "./lib/viewers";
export { ViewerAPIError } from "./lib/viewers";
export { CommunityAPIError } from "./lib/community";
