export { createClient } from "./lib/client";
export type { ClientOptions } from "./lib/client";
export { createAuthClient } from "./lib/auth";
export type { AuthClientOptions, AuthRequestOptions } from "./lib/auth";
export { DEFAULT_API_BASE_URL, DEFAULT_INTERNAL_API_BASE_URL } from "./lib/constants";
export type {
  Video,
  VideoAttachment,
  VideoDownloadUrls,
  VideoSubtitles,
  VideoTranscript,
  VideoMetadata,
  Playlist,
  MenuItem,
  Settings,
  Portal,
  PortalDisplay,
  PortalHero,
  CustomRedirect,
  AnalyticsProvider,
  PortalLayout,
  PortalNavigation,
  PortalTheme,
  AssistantConfig,
  ThemeConfig,
  ThemeColors,
  Account,
  AccountAI,
  MultimodalCapability,
  ConversationStarter,
  ConversationStarterSource,
  ListConversationStartersOptions,
  Segment,
  Source,
  Citation,
  AIUsage,
  AIEvent,
  AIResponse,
  VoiceStatus,
  VoiceEndReason,
  VoiceSpeaker,
  VoiceCaptionSegment,
  VoiceCaptionTurn,
  VoiceAudioLevels,
  VoiceSessionOptions,
  VoiceSession,
  ImageInput,
  ChatOptions,
  SearchOptions,
  AIContextMessage,
  RecommendationsOptions,
  RecommendationsResponse,
  Recommendation,
  RecommendationVideo,
  // Deprecated type aliases (kept for backward compatibility)
  AskOptions,
  RecommendOptions,
  RecommendResponse,
  Conversation,
  ConversationMessage,
  ConversationMetadata,
  // Viewers API
  Viewer,
  ViewerProgress,
  ListProgressOptions,
  CreateViewerData,
  UpdateViewerData,
  SaveProgressData,
  ProgressListMeta,
  // Session Management API
  AuthSessionPlatform,
  AuthSessionCreateData,
  AuthActiveSession,
  AuthSessionCreatedResponse,
  AuthSessionBypassedResponse,
  AuthSessionChallengeResponse,
  AuthSessionCreateResponse,
  AuthSessionListResponse,
  AuthSessionVerifyResponse,
  AuthSessionRevokeResponse,
  AuthSessionRevokeOthersResponse,
  AuthChallengeResendResponse,
  NotificationProvider,
  RegisterDeviceData,
  RegisterDeviceResponse,
  SessionManagementViewerState,
  SessionManagementViewerStateResponse,
  SessionManagementViewerResolveResponse,
  SessionManagementSession,
  TravelVerdict,
  SessionManagementViewerSessionsResponse,
  SessionManagementRevokeSessionResponse,
  SessionManagementRevokeAllResponse,
  // Video list options
  ListVideosOptions,
  ListVideosLatestOptions,
  ListVideosIndexOptions,
  // Notification API
  NotificationChannels,
  NotificationPreferencesResponse,
  NotificationChannelUpdate,
  UpdateNotificationPreferencesData,
  // Community API
  Post,
  PostAuthor,
  UserSummary,
  ReactionSummary,
  CommentSummary,
  CommentReactionSummary,
  CommentThread,
  Reply,
  Comment,
  ReactionResponse,
  MentionSkippedReport,
  CommunityPostCreateResponse,
  CommunityCommentCreateResponse,
  Mention,
  ListPostsOptions,
  ListMentionsOptions,
  MentionsUnreadCountResponse,
  MarkMentionsReadData,
  MarkMentionsReadResponse,
  CreatePostData,
  UpdatePostData,
  CreateCommentData,
  PaginationMeta,
  PaginatedResponse,
} from "./lib/types";

export type { ViewerLookupParams } from "./lib/viewers";
export { ViewerAPIError } from "./lib/viewers";
export type { SessionManagementRevokeOptions } from "./lib/session-management";
export { SessionManagementAPIError } from "./lib/session-management";
export {
  AuthAPIError,
  SessionManagementUnavailableError,
} from "./lib/auth";
export { NotificationsAPIError } from "./lib/notifications";
export { ConversationStartersAPIError } from "./lib/conversation-starters";
export { CommunityAPIError } from "./lib/community";
export { AIAPIError } from "./lib/ai";
export { VoiceAPIError } from "./lib/voice";
export { appendVoiceCaption, splitVoiceTimestamps } from "./lib/voice-captions";
