name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write  # For npm provenance

jobs:
  release:
    name: Release to npm
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for changelog generation
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.2
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run CI checks
        run: |
          pnpm run lint
          pnpm run build
      
      - name: Verify version matches tag
        run: |
          PACKAGE_VERSION="v$(node -p "require('./package.json').version")"
          if [ "$PACKAGE_VERSION" != "${{ github.ref_name }}" ]; then
            echo "Error: Package version ($PACKAGE_VERSION) doesn't match tag (${{ github.ref_name }})"
            exit 1
          fi
      
      - name: Check npm access
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish to npm with provenance
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          body: |
            ## What's Changed
            
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
            
            ## Installation
            
            ```bash
            npm install @boldvideo/bold-js@${{ github.ref_name }}
            ```
            
            ```bash
            pnpm add @boldvideo/bold-js@${{ github.ref_name }}
            ```
            
            ```bash
            yarn add @boldvideo/bold-js@${{ github.ref_name }}
            ```